export const THEMES = {
  lumina: {
    name: 'Lumina Dark',
    type: 'dark',
    colors: {
      '--primary': '#d0bcff',
      '--on-primary': '#3c0091',
      '--primary-container': '#4f378b',
      '--on-primary-container': '#eaddff',
      '--secondary': '#44e2cd',
      '--on-secondary': '#003731',
      '--background': '#15121b',
      '--on-background': '#e7e0ed',
      '--surface': '#15121b',
      '--on-surface': '#e7e0ed',
      '--on-surface-variant': '#cbc3d7',
      '--surface-container-lowest': '#0f0d15',
      '--surface-container-low': '#1d1a23',
      '--surface-container': '#211e27',
      '--surface-container-high': '#2c2832',
      '--surface-container-highest': '#37333d',
      '--outline': '#958ea0',
      '--outline-variant': '#494454',
      '--calendar-filter': 'invert(1)'
    }
  },
  midnight: {
    name: 'Midnight Blue',
    type: 'dark',
    colors: {
      '--primary': '#60a5fa',
      '--on-primary': '#1e3a8a',
      '--primary-container': '#1e3a8a',
      '--on-primary-container': '#dbeafe',
      '--secondary': '#818cf8',
      '--on-secondary': '#312e81',
      '--background': '#020617',
      '--on-background': '#f1f5f9',
      '--surface': '#020617',
      '--on-surface': '#f1f5f9',
      '--on-surface-variant': '#94a3b8',
      '--surface-container-lowest': '#000000',
      '--surface-container-low': '#0f172a',
      '--surface-container': '#1e293b',
      '--surface-container-high': '#334155',
      '--surface-container-highest': '#475569',
      '--outline': '#64748b',
      '--outline-variant': '#334155',
      '--calendar-filter': 'invert(1)'
    }
  },
  obsidian: {
    name: 'Obsidian Red',
    type: 'dark',
    colors: {
      '--primary': '#f87171',
      '--on-primary': '#7f1d1d',
      '--primary-container': '#7f1d1d',
      '--on-primary-container': '#fee2e2',
      '--secondary': '#fb923c',
      '--on-secondary': '#7c2d12',
      '--background': '#0c0a09',
      '--on-background': '#f5f5f4',
      '--surface': '#0c0a09',
      '--on-surface': '#f5f5f4',
      '--on-surface-variant': '#a8a29e',
      '--surface-container-lowest': '#000000',
      '--surface-container-low': '#1c1917',
      '--surface-container': '#292524',
      '--surface-container-high': '#44403c',
      '--surface-container-highest': '#57534e',
      '--outline': '#78716c',
      '--outline-variant': '#44403c',
      '--calendar-filter': 'invert(1)'
    }
  },
  lavender_mist: {
    name: 'Lavender Mist',
    type: 'light',
    colors: {
      '--primary': '#6b38d4',
      '--on-primary': '#ffffff',
      '--primary-container': '#e9ddff',
      '--on-primary-container': '#22005d',
      '--secondary': '#7c4dff',
      '--on-secondary': '#ffffff',
      '--background': '#fbf8ff',
      '--on-background': '#1b1b1f',
      '--surface': '#fbf8ff',
      '--on-surface': '#1b1b1f',
      '--on-surface-variant': '#46464f',
      '--surface-container-lowest': '#fdfbff',
      '--surface-container-low': '#f5f2fa',
      '--surface-container': '#f0ecf5',
      '--surface-container-high': '#eae6ef',
      '--surface-container-highest': '#e4e1e9',
      '--outline': '#777680',
      '--outline-variant': '#c7c5d0',
      '--calendar-filter': 'invert(0)'
    }
  },
  azure_breeze: {
    name: 'Azure Breeze',
    type: 'light',
    colors: {
      '--primary': '#0061a4',
      '--on-primary': '#ffffff',
      '--primary-container': '#d1e4ff',
      '--on-primary-container': '#001d36',
      '--secondary': '#535f70',
      '--on-secondary': '#ffffff',
      '--background': '#f8f9ff',
      '--on-background': '#191c20',
      '--surface': '#f8f9ff',
      '--on-surface': '#191c20',
      '--on-surface-variant': '#43474e',
      '--surface-container-lowest': '#f8fbff',
      '--surface-container-low': '#f0f3f9',
      '--surface-container': '#eaedf4',
      '--surface-container-high': '#e4e8ee',
      '--surface-container-highest': '#dee2e9',
      '--outline': '#73777f',
      '--outline-variant': '#c3c7cf',
      '--calendar-filter': 'invert(0)'
    }
  },
  solar: {
    name: 'Solar Breeze',
    type: 'light',
    colors: {
      '--primary': '#934b00',
      '--on-primary': '#ffffff',
      '--primary-container': '#ffdbcb',
      '--on-primary-container': '#2f1500',
      '--secondary': '#825500',
      '--on-secondary': '#ffffff',
      '--background': '#fffbff',
      '--on-background': '#201b17',
      '--surface': '#fffbff',
      '--on-surface': '#201b17',
      '--on-surface-variant': '#52443c',
      '--surface-container-lowest': '#fff8f5',
      '--surface-container-low': '#fdf2e9',
      '--surface-container': '#f7ece2',
      '--surface-container-high': '#f1e6dc',
      '--surface-container-highest': '#ebe0d7',
      '--outline': '#85736b',
      '--outline-variant': '#d7c2b8',
      '--calendar-filter': 'invert(0)'
    }
  }
};
